[package]
name = "libgcc"
version = "15.2.0"
license = "GPL-3.0 WITH GCC-exception-3.1"
pre_bootstrap = false
description = "GCC runtime library (libgcc_s.so)"

[build]
build = ""
install = ""

[depends]
runtime = ["musl"]
build = []
