[package]
name = "jpkg"
version = "1.0.1"
license = "MIT"
description = "jonerix package manager"

[build]
build = ""
install = ""

[depends]
runtime = ["musl", "curl", "zstd", "libarchive"]
build = []
