[package]
name = "zsh"
version = "5.9"
license = "MIT"
pre_bootstrap = false
description = "Z shell — bash-compatible permissive shell for build scripts"

[build]
build = ""
install = ""

[depends]
runtime = ["musl", "ncurses"]
build = []
