[package]
name = "musl"
version = "1.2.6"
license = "MIT"
pre_bootstrap = false
description = "Lightweight, fast, and standards-conformant C library"

[build]
system = "custom"
build = ""
install = ""

[depends]
runtime = []
build = []
