[package]
name = "dhcpcd"
version = "10.1.0"
license = "BSD-2-Clause"
pre_bootstrap = false
description = "RFC2131-compliant DHCP client daemon"

[build]
system = "custom"
build = ""
install = ""

[depends]
runtime = ["musl"]
build = []
