[package]
name = "pico"
version = "2.26"
license = "Apache-2.0"
pre_bootstrap = true
description = "Easy text editor from the Alpine email suite"

[build]
system = "custom"
build = """
set -e
apk add --no-cache alpine
install -Dm755 /usr/bin/pico "${DESTDIR}/bin/pico"
"""
install = ""

[depends]
runtime = ["ncurses"]
build = []
