#!/bin/sh
# install/wsl/build-rootfs.sh
#
# Build a minimal jonerix WSL2 rootfs tarball inside the current Alpine
# container.  Produces:
#   jonerix-rootfs-<arch>.tar.gz
#
# Usage (run as root inside Alpine):
#   sh build-rootfs.sh
#
# Environment variables:
#   ARCH        — override detected architecture (x86_64 | aarch64)
#   GITHUB_REPO — GitHub repository slug (default: stormj-UH/jonerix)
#   PKG_RELEASE — GitHub release tag for packages (default: packages)
#   STAGING     — staging directory (default: /tmp/jonerix-rootfs)
#   OUTPUT_DIR  — where to write the tarball (default: current directory)

set -e

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
GITHUB_REPO="${GITHUB_REPO:-stormj-UH/jonerix}"
PKG_RELEASE="${PKG_RELEASE:-packages}"
STAGING="${STAGING:-/tmp/jonerix-rootfs}"
OUTPUT_DIR="${OUTPUT_DIR:-$(pwd)}"
PKG_BASE_URL="https://github.com/${GITHUB_REPO}/releases/download/${PKG_RELEASE}"

# Detect architecture if not set
if [ -z "$ARCH" ]; then
    machine="$(uname -m)"
    case "$machine" in
        x86_64)  ARCH="x86_64" ;;
        aarch64) ARCH="aarch64" ;;
        arm64)   ARCH="aarch64" ;;
        *)       ARCH="$machine" ;;
    esac
fi

echo "=== Building jonerix WSL rootfs for ${ARCH} ==="
echo "    Package repo : ${PKG_BASE_URL}"
echo "    Staging dir  : ${STAGING}"
echo "    Output dir   : ${OUTPUT_DIR}"

# ---------------------------------------------------------------------------
# 1. Install host-side build tools (curl, zstd for jpkg install)
# ---------------------------------------------------------------------------
echo "--- Installing host build tools ---"
apk add --no-cache curl zstd tar

# ---------------------------------------------------------------------------
# 2. Build the jpkg binary if not already present
# ---------------------------------------------------------------------------
if ! command -v jpkg > /dev/null 2>&1; then
    echo "--- Building jpkg ---"
    apk add --no-cache clang lld musl-dev make zstd-dev zstd-static
    # WORKSPACE is set by CI; fall back to the repo root relative to this script
    SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
    REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
    cd "${REPO_ROOT}/packages/jpkg"
    make CC=clang LDFLAGS="-static -fuse-ld=lld" jpkg
    install -m 755 jpkg /usr/local/bin/jpkg
    cd -
fi

# ---------------------------------------------------------------------------
# 3. Prepare staging directory (clean slate)
# ---------------------------------------------------------------------------
echo "--- Preparing staging directory ---"
rm -rf "${STAGING}"
mkdir -p "${STAGING}"

# FHS skeleton
for d in \
    bin lib etc boot dev proc sys run tmp \
    home root \
    var/log var/cache/jpkg var/db/jpkg/installed \
    etc/jpkg/keys \
    etc/jpkg
do
    mkdir -p "${STAGING}/${d}"
done

# Merged-usr: /usr -> / so /usr/bin, /usr/lib, etc. resolve correctly
ln -sf . "${STAGING}/usr"

# Fix permissions
chmod 0700 "${STAGING}/root"
chmod 1777 "${STAGING}/tmp"

# ---------------------------------------------------------------------------
# 4. Create /etc/os-release
# ---------------------------------------------------------------------------
echo "--- Writing /etc/os-release ---"
cat > "${STAGING}/etc/os-release" << 'EOF'
NAME="jonerix"
ID=jonerix
VERSION_ID=1.0
PRETTY_NAME="jonerix 1.0"
HOME_URL="https://github.com/stormj-UH/jonerix"
BUG_REPORT_URL="https://github.com/stormj-UH/jonerix/issues"
EOF

# ---------------------------------------------------------------------------
# 5. Create /etc/jpkg/repos.conf
# ---------------------------------------------------------------------------
echo "--- Writing /etc/jpkg/repos.conf ---"
cat > "${STAGING}/etc/jpkg/repos.conf" << EOF
# jonerix package repository configuration
# Generated by install/wsl/build-rootfs.sh

[general]
arch = "${ARCH}"

[repo]
url = "${PKG_BASE_URL}"
EOF

# ---------------------------------------------------------------------------
# 6. Create minimal /etc/passwd, /etc/group, /etc/shadow, /etc/shells
# ---------------------------------------------------------------------------
echo "--- Writing base /etc files ---"
cat > "${STAGING}/etc/passwd" << 'EOF'
root:x:0:0:root:/root:/bin/mksh
nobody:x:65534:65534:nobody:/nonexistent:/bin/false
EOF

cat > "${STAGING}/etc/group" << 'EOF'
root:x:0:
nobody:x:65534:
EOF

cat > "${STAGING}/etc/shadow" << 'EOF'
root:::0:99999:7:::
nobody:!:::::::
EOF
chmod 0600 "${STAGING}/etc/shadow"

cat > "${STAGING}/etc/shells" << 'EOF'
/bin/mksh
/bin/sh
EOF

cat > "${STAGING}/etc/hostname" << 'EOF'
jonerix
EOF

cat > "${STAGING}/etc/resolv.conf" << 'EOF'
nameserver 1.1.1.1
nameserver 8.8.8.8
EOF

# Minimal profile
cat > "${STAGING}/etc/profile" << 'EOF'
# /etc/profile -- jonerix login profile
export PATH="/bin"
[ -d "/usr/local/bin" ] && export PATH="/usr/local/bin:$PATH"

if [ "$(id -u)" -eq 0 ]; then
    PS1='\h:\w# '
else
    PS1='\u@\h:\w$ '
fi
export PS1

umask 022
export CHARSET="UTF-8"
export LANG="C.UTF-8"
export LC_ALL="C.UTF-8"
export EDITOR="nvi"
export PAGER="less"

alias ls='ls --color=auto'
alias ll='ls -la'

[ -f "$HOME/.profile" ] && . "$HOME/.profile"
EOF

# wsl.conf — tells WSL2 about the default user and init
cat > "${STAGING}/etc/wsl.conf" << 'EOF'
[user]
default = root

[interop]
enabled = true
appendWindowsPath = false

[automount]
enabled = true
mountFsTab = true
EOF

# ---------------------------------------------------------------------------
# 7. Download and install packages into the staging dir via jpkg
# ---------------------------------------------------------------------------
echo "--- Fetching packages from release ---"
CACHE_DIR="/var/cache/jpkg"
mkdir -p "${CACHE_DIR}"

# Helper: download a .jpkg from the packages release
download_jpkg() {
    pkg_name="$1"
    # Try arch-specific filename first, then generic
    for fname in "${pkg_name}-"*"-${ARCH}.jpkg" "${pkg_name}-"*".jpkg"; do
        url="${PKG_BASE_URL}/${fname}"
        dest="${CACHE_DIR}/${fname}"
        # We don't know the version, so use curl with glob disabled and
        # let the INDEX tell us.  Instead, we list the release and filter.
        break
    done
}

# Fetch the INDEX so we can resolve exact filenames
echo "    Downloading INDEX.zst ..."
INDEX_ZST="${CACHE_DIR}/INDEX.zst"
curl -fsSL "${PKG_BASE_URL}/INDEX.zst" -o "${INDEX_ZST}" || {
    echo "WARNING: Could not download INDEX.zst — package install skipped."
    INDEX_ZST=""
}

# Parse INDEX.zst for package filenames (name + version + arch -> filename)
install_pkg() {
    pkg="$1"
    [ -z "${INDEX_ZST}" ] && { echo "  SKIP ${pkg} (no index)"; return 0; }

    # Decompress index to a temp file
    INDEX_PLAIN="${CACHE_DIR}/INDEX"
    [ -f "${INDEX_PLAIN}" ] || zstd -d -f "${INDEX_ZST}" -o "${INDEX_PLAIN}" 2>/dev/null || true

    # Extract version for this package+arch section
    # Section key is "name-arch" in the INDEX
    section="${pkg}-${ARCH}"
    version=$(awk -v sec="[${section}]" '
        $0 == sec { found=1; next }
        found && /^\[/ { found=0 }
        found && /^version / { gsub(/.*= *"|"/, ""); print; exit }
    ' "${INDEX_PLAIN}")

    if [ -z "$version" ]; then
        # Fall back to generic section
        version=$(awk -v sec="[${pkg}]" '
            $0 == sec { found=1; next }
            found && /^\[/ { found=0 }
            found && /^version / { gsub(/.*= *"|"/, ""); print; exit }
        ' "${INDEX_PLAIN}")
    fi

    if [ -z "$version" ]; then
        echo "  WARNING: ${pkg} not found in INDEX, skipping."
        return 0
    fi

    # Try arch-suffixed filename first
    for fname in "${pkg}-${version}-${ARCH}.jpkg" "${pkg}-${version}.jpkg"; do
        pkgfile="${CACHE_DIR}/${fname}"
        if [ ! -f "${pkgfile}" ]; then
            echo "    Downloading ${fname} ..."
            curl -fsSL "${PKG_BASE_URL}/${fname}" -o "${pkgfile}" 2>/dev/null || { rm -f "${pkgfile}"; continue; }
        fi
        if [ -f "${pkgfile}" ]; then
            echo "    Installing ${fname} into staging ..."
            # jpkg install with --root to target the staging dir
            jpkg install "${pkg}" --root "${STAGING}" \
                --pkg-file "${pkgfile}" 2>/dev/null || \
            # Fallback: extract the payload tarball directly
            extract_jpkg "${pkgfile}" "${STAGING}"
            return 0
        fi
    done

    echo "  WARNING: Could not download ${pkg}, skipping."
}

# Fallback extractor: jpkg files are a simple binary format.
# Header: magic(4) + version(4) + meta_len(4) + meta(meta_len) + payload(tar.zst)
extract_jpkg() {
    jpkgfile="$1"
    destdir="$2"
    echo "    Extracting ${jpkgfile} (raw) ..."
    # Read meta_len (4 bytes at offset 8, big-endian)
    meta_len=$(dd if="${jpkgfile}" bs=1 skip=8 count=4 2>/dev/null | od -An -tu4 | tr -d ' \n')
    [ -z "$meta_len" ] || [ "$meta_len" -eq 0 ] && { echo "    WARNING: bad jpkg header"; return 1; }
    skip=$((12 + meta_len))
    dd if="${jpkgfile}" bs=1 skip="${skip}" 2>/dev/null | \
        zstd -d 2>/dev/null | \
        tar -xf - -C "${destdir}" 2>/dev/null || true
}

# Install the minimal set of packages
echo "--- Installing packages: musl, mksh, toybox ---"
for pkg in musl mksh toybox; do
    echo "  -> ${pkg}"
    install_pkg "${pkg}"
done

# Install jpkg itself into the rootfs
echo "  -> jpkg"
install_pkg "jpkg"

# If jpkg install didn't place jpkg binary, copy our host binary
if [ ! -f "${STAGING}/bin/jpkg" ]; then
    echo "    Copying host jpkg binary as fallback ..."
    install -Dm755 "$(command -v jpkg)" "${STAGING}/bin/jpkg"
fi

# Ensure /bin/sh exists (toybox or busybox provides it; mksh fallback)
if [ ! -e "${STAGING}/bin/sh" ]; then
    if [ -f "${STAGING}/bin/mksh" ]; then
        ln -sf mksh "${STAGING}/bin/sh"
    fi
fi

# ---------------------------------------------------------------------------
# 8. Install the public signing key
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
PUBKEY="${REPO_ROOT}/config/defaults/etc/jpkg/keys/jonerix.pub"
if [ -f "${PUBKEY}" ]; then
    echo "--- Installing signing key ---"
    mkdir -p "${STAGING}/etc/jpkg/keys"
    cp "${PUBKEY}" "${STAGING}/etc/jpkg/keys/jonerix.pub"
fi

# ---------------------------------------------------------------------------
# 9. Pack the rootfs
# ---------------------------------------------------------------------------
OUTPUT_FILE="${OUTPUT_DIR}/jonerix-rootfs-${ARCH}.tar.gz"
echo "--- Creating tarball: ${OUTPUT_FILE} ---"
mkdir -p "${OUTPUT_DIR}"
tar -C "${STAGING}" -czf "${OUTPUT_FILE}" \
    --exclude='./proc/*' \
    --exclude='./sys/*' \
    --exclude='./dev/*' \
    .
echo "Done. Rootfs: $(ls -lh "${OUTPUT_FILE}" | awk '{print $5}') — ${OUTPUT_FILE}"
