[package]
name = "nvi"
version = "2.2.1"
license = "BSD-3-Clause"
pre_bootstrap = true
description = "nvi2 text editor (reimplementation of Berkeley vi)"

[build]
system = "custom"
build = """
set -e
apk add --no-cache alpine
install -Dm755 /usr/bin/pico "${DESTDIR}/bin/vi"
install -Dm755 /usr/bin/pico "${DESTDIR}/bin/nvi"
"""
install = ""

[depends]
runtime = ["musl", "ncurses"]
build = []
