[package]
name = "nodejs"
version = "24.14.1"
license = "MIT"
pre_bootstrap = false
description = "JavaScript runtime built on V8"

[build]
system = "custom"
build = ""
install = ""

[depends]
runtime = ["musl", "libcxx", "libatomic"]
build = []
