[package]
name = "fastfetch"
version = "2.36.1"
license = "MIT"
pre_bootstrap = false
description = "Feature-rich system information tool"

[source]
url = "https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/2.36.1.tar.gz"
sha256 = "490d5b971dd7fac4c31018354904fdd5e2c409924ba868157bda3bfe1fb5c485"

[build]
system = "cmake"
configure = "cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=/ -DFASTFETCH_BUILD_TESTS=OFF"
build = "samu -C build -j$(nproc)"
install = """DESTDIR=$DESTDIR samu -C build install
if [ -d "$DESTDIR/usr" ]; then cp -a "$DESTDIR/usr/." "$DESTDIR/" && rm -rf "$DESTDIR/usr"; fi
if [ -d "$DESTDIR/lib64" ]; then cp -a "$DESTDIR/lib64/." "$DESTDIR/lib/" && rm -rf "$DESTDIR/lib64"; fi
find $DESTDIR/bin -type f -exec llvm-strip --strip-all {} \; 2>/dev/null || true
find $DESTDIR/lib -name "*.so*" -type f -exec llvm-strip --strip-unneeded {} \; 2>/dev/null || true"""

[depends]
runtime = ["musl", "libcxx"]
build = ["clang", "cmake", "samurai"]
