[package]
name = "fastfetch"
version = "2.36.1"
license = "MIT"
pre_bootstrap = false
description = "Feature-rich system information tool"

[build]
system = "custom"
build = ""
install = ""

[depends]
runtime = ["musl"]
build = []
