[package]
name = "pigz"
version = "2.8"
license = "Zlib"
pre_bootstrap = false
description = "Parallel implementation of gzip"

[build]
system = "custom"
build = ""
install = ""

[depends]
runtime = ["musl"]
build = []
