[package]
name = "curl"
version = "8.11.1"
license = "MIT"
pre_bootstrap = false
description = "Command-line tool and library for transferring data with URLs"

[source]
url = "https://curl.se/download/curl-8.11.1.tar.gz"
sha256 = "a889ac9dbba3644271bd9d1302b5c22a088893719b72be3487bc3d401e5c4e80"

[build]
system = "cmake"
configure = """cmake -B build -G Ninja \
  -DCURL_USE_OPENSSL=ON \
  -DBUILD_SHARED_LIBS=ON \
  -DBUILD_CURL_EXE=ON \
  -DCURL_DISABLE_LDAP=ON \
  -DCURL_USE_LIBSSH2=OFF \
  -DBUILD_TESTING=OFF \
  -DCMAKE_INSTALL_PREFIX=/ \
  -DCMAKE_INSTALL_LIBDIR=lib \
  -DCMAKE_C_COMPILER=clang \
  -DCMAKE_BUILD_TYPE=Release"""
build = "samu -C build -j$(nproc)"
install = """DESTDIR=$DESTDIR samu -C build install
if [ -d "$DESTDIR/usr" ]; then cp -a "$DESTDIR/usr/." "$DESTDIR/" && rm -rf "$DESTDIR/usr"; fi
if [ -d "$DESTDIR/lib64" ]; then cp -a "$DESTDIR/lib64/." "$DESTDIR/lib/" && rm -rf "$DESTDIR/lib64"; fi"""

[depends]
runtime = ["musl", "openssl", "zlib"]
build = ["clang", "cmake", "samurai"]
