[package]
name = "curl"
version = "8.11.1"
license = "MIT"
pre_bootstrap = false
description = "Command-line tool and library for transferring data with URLs"

[build]
system = "custom"
build = ""
install = ""

[depends]
runtime = ["musl", "openssl"]
build = []
