[package]
name = "zlib"
version = "1.3.2-r1"
license = "Zlib"
description = "General-purpose compression library"

[source]
url = "https://github.com/madler/zlib/releases/download/v1.3.2/zlib-1.3.2.tar.gz"
sha256 = "bb329a0a2cd0274d05519d61c667c062e06990d72e125ee2dfa8de64f0119d16"

[build]
system = "custom"
configure = """CC=clang \
CFLAGS="-O2 -fomit-frame-pointer -fPIC" \
LDFLAGS="-fuse-ld=lld" \
LDSHARED="clang -shared -Wl,--undefined-version,-soname,libz.so.1,--version-script,zlib.map" \
./configure --prefix=/ --libdir=/lib --includedir=/include --shared"""
build = "make -j$(nproc)"
install = """make install DESTDIR=$DESTDIR
if [ -d "$DESTDIR/usr" ]; then cp -a "$DESTDIR/usr/." "$DESTDIR/" && rm -rf "$DESTDIR/usr"; fi
if [ -d "$DESTDIR/lib64" ]; then cp -a "$DESTDIR/lib64/." "$DESTDIR/lib/" && rm -rf "$DESTDIR/lib64"; fi
find $DESTDIR/bin -type f -exec llvm-strip --strip-all {} \; 2>/dev/null || true
find $DESTDIR/lib -name '*.so*' -exec llvm-strip --strip-unneeded {} \; 2>/dev/null || true"""

[depends]
runtime = ["musl"]
build = ["clang", "make"]
