[package]
name = "bc"
version = "7.0.3"
license = "BSD-2-Clause"
pre_bootstrap = false
description = "Implementation of the bc calculator language"

[build]
system = "custom"
build = ""
install = ""

[depends]
runtime = ["musl"]
build = []
