[package]
name = "bc"
version = "7.0.3"
license = "BSD-2-Clause"
pre_bootstrap = false
description = "Implementation of the bc calculator language"

[source]
url = "https://github.com/gavinhoward/bc/releases/download/7.0.3/bc-7.0.3.tar.xz"
sha256 = "FIXME"

[build]
system = "custom"
build = """CFLAGS="-O2 -fomit-frame-pointer" CC=clang ./configure.sh --prefix=/ --bindir=/bin --disable-generated-tests --disable-man-pages
make -j$(nproc)"""
install = """make DESTDIR=$DESTDIR install
if [ -d "$DESTDIR/usr" ]; then cp -a "$DESTDIR/usr/." "$DESTDIR/" && rm -rf "$DESTDIR/usr"; fi
if [ -d "$DESTDIR/lib64" ]; then cp -a "$DESTDIR/lib64/." "$DESTDIR/lib/" && rm -rf "$DESTDIR/lib64"; fi
find $DESTDIR/bin -type f -exec llvm-strip --strip-all {} \; 2>/dev/null || true
find $DESTDIR/lib -name "*.so*" -type f -exec llvm-strip --strip-unneeded {} \; 2>/dev/null || true"""

[depends]
runtime = ["musl"]
build = ["clang", "make"]
