[package]
name = "xz"
version = "5.8.2"
license = "0BSD"
pre_bootstrap = false
description = "XZ compression utilities and liblzma"

[build]
system = "custom"
build = ""
install = ""

[depends]
runtime = ["musl"]
build = []
