[package]
name = "byacc"
version = "20241231"
license = "public domain"
pre_bootstrap = false
description = "Berkeley Yacc parser generator"

[build]
system = "custom"
build = ""
install = ""

[depends]
runtime = ["musl"]
build = []
