[package]
name = "dropbear"
version = "2024.86"
license = "MIT"
pre_bootstrap = false
description = "Lightweight SSH server and client"

[build]
system = "custom"
build = ""
install = ""

[depends]
runtime = ["musl"]
build = []
