[package]
name = "ncurses"
version = "6.5"
license = "MIT"
pre_bootstrap = false
description = "Terminal handling library"

[source]
url = "https://invisible-island.net/archives/ncurses/ncurses-6.5.tar.gz"
sha256 = "136d91bc269a9a5785e5f9e980bc76ab57428f604ce3e5a5a90cebc767971cc6"

[build]
system = "autoconf"
configure = "CFLAGS=\"-O2 -fomit-frame-pointer\" ./configure --prefix=/ --with-shared --without-debug --enable-widec --without-cxx --without-manpages --disable-stripping CC=clang"
build = "make -j$(nproc)"
install = """make DESTDIR=$DESTDIR install
if [ -d "$DESTDIR/usr" ]; then cp -a "$DESTDIR/usr/." "$DESTDIR/" && rm -rf "$DESTDIR/usr"; fi
if [ -d "$DESTDIR/lib64" ]; then cp -a "$DESTDIR/lib64/." "$DESTDIR/lib/" && rm -rf "$DESTDIR/lib64"; fi
find $DESTDIR/bin -type f -exec llvm-strip --strip-all {} \; 2>/dev/null || true
find $DESTDIR/lib -name "*.so*" -type f -exec llvm-strip --strip-unneeded {} \; 2>/dev/null || true"""

[depends]
runtime = []
build = ["clang", "make"]
