[package]
name = "ncurses"
version = "6.5"
license = "MIT"
pre_bootstrap = false
description = "Terminal handling library"

[build]
system = "custom"
build = ""
install = ""

[depends]
runtime = []
build = []
