[package]
name = "containerd"
version = "2.2.2"
license = "Apache-2.0"
pre_bootstrap = false
description = "Industry-standard container runtime"

[build]
system = "custom"
build = ""
install = ""

[depends]
runtime = ["musl"]
build = []
