[package]
name = "tmux"
version = "3.6a"
license = "ISC"
description = "Terminal multiplexer"

[source]
url = "https://github.com/tmux/tmux/releases/download/3.6a/tmux-3.6a.tar.gz"
sha256 = "b6d8d9c76585db8ef5fa00d4931902fa4b8cbe8166f528f44fc403961a3f3759"

[build]
system = "custom"
build = """set -e
ulimit -n 65536

# jonerix ships libncursesw only; tmux configure looks for libncurses
ln -sf libncursesw.so.6 /lib/libncurses.so
ln -sf libncursesw.so.6 /lib/libncurses.so.6

GREP=/bin/grep EGREP="/bin/grep -E" FGREP="/bin/grep -F" \
  ./configure \
    --prefix=/ \
    --bindir=/bin \
    --sysconfdir=/etc \
    --disable-utf8proc \
    CC=clang \
    CFLAGS="-O2 -fomit-frame-pointer --rtlib=compiler-rt --unwindlib=libunwind -I/include/ncursesw" \
    LDFLAGS="-fuse-ld=lld --rtlib=compiler-rt --unwindlib=libunwind -Wl,--disable-new-dtags"

make -j$(nproc)
"""
install = """set -e
make DESTDIR=$DESTDIR install
if [ -d "$DESTDIR/usr" ]; then cp -a "$DESTDIR/usr/." "$DESTDIR/" && rm -rf "$DESTDIR/usr"; fi
if [ -d "$DESTDIR/lib64" ]; then cp -a "$DESTDIR/lib64/." "$DESTDIR/lib/" && rm -rf "$DESTDIR/lib64"; fi
rm -rf "$DESTDIR/share/doc" "$DESTDIR/share/man"
find "$DESTDIR/bin" -type f -exec llvm-strip --strip-all {} \; 2>/dev/null || true
"""

[depends]
runtime = ["musl", "ncurses", "libevent"]
build = ["clang", "make", "exproxide", "libevent", "ncurses", "jonerix-headers", "byacc"]
