[package]
name = "lz4"
version = "1.10.0"
license = "BSD-2-Clause"
pre_bootstrap = false
description = "Extremely fast lossless compression library and tool"

[build]
system = "custom"
build = ""
install = ""

[depends]
runtime = ["musl"]
build = []
