[package]
name = "bmake"
version = "20240808"
license = "MIT"
pre_bootstrap = false
description = "Portable version of NetBSD make"

[build]
system = "custom"
build = ""
install = ""

[depends]
runtime = ["musl"]
build = []
