[package]
name = "bmake"
version = "20240808"
license = "MIT"
pre_bootstrap = false
description = "Portable version of NetBSD make"

[source]
url = "sources/bmake-20240808.tar.gz"  # vendored in sources/
sha256 = "b59189251b483decd4492f1f74387b2a584c03d5aa4637cd48b38ec62b9c0848"

[build]
system = "custom"
build = "sh boot-strap --prefix=/ --install-destdir=$DESTDIR op=install"
install = """if [ -d "$DESTDIR/usr" ]; then cp -a "$DESTDIR/usr/." "$DESTDIR/" && rm -rf "$DESTDIR/usr"; fi
if [ -d "$DESTDIR/lib64" ]; then cp -a "$DESTDIR/lib64/." "$DESTDIR/lib/" && rm -rf "$DESTDIR/lib64"; fi
find $DESTDIR/bin -type f -exec llvm-strip --strip-all {} \; 2>/dev/null || true
find $DESTDIR/lib -name "*.so*" -type f -exec llvm-strip --strip-unneeded {} \; 2>/dev/null || true"""

[depends]
runtime = ["musl"]
build = ["clang"]
