[package]
name = "nerdctl"
version = "2.2.1"
license = "Apache-2.0"
pre_bootstrap = false
description = "Docker-compatible CLI for containerd"

[build]
system = "custom"
build = ""
install = ""

[depends]
runtime = ["musl", "containerd", "runc", "cni-plugins"]
build = []
