# jcarp default configuration.
# The service is not enabled by default. Edit this file, then:
#   rc-update add jcarp default
#   rc-service jcarp start

interface=eth1
link_mode=macvlan-bridge
link_name=jcarp1
vhid=1
advbase=1
advskew=100
demote=0
preempt=false
peer=224.0.0.18
vip=192.168.1.1
mac=virtual
passphrase=change-me
