[package]
name = "llvm"
version = "21"
license = "Apache-2.0"
pre_bootstrap = false
description = "LLVM compiler infrastructure with clang and lld"

[build]
system = "custom"
build = ""
install = ""

[depends]
runtime = ["musl", "zstd"]
build = []
