[package]
name = "micro"
version = "2.0.15"
license = "MIT"
description = "Modern terminal text editor (intuitive keybindings, syntax highlighting)"

[source]
url = "https://github.com/zyedidia/micro/releases/download/v2.0.15/micro-2.0.15-src.tar.gz"
sha256 = "a5668fcd8bc852964468e84dee78f93c482ab25e2a9767a238eb471871669e0f"

[build]
system = "custom"
build = """CGO_ENABLED=0 go build -mod=vendor -trimpath -ldflags="-s -w" ./cmd/micro"""
install = """install -Dm755 micro $DESTDIR/bin/micro
ln -sf micro $DESTDIR/bin/editor
ln -sf micro $DESTDIR/bin/vi
if [ -d "$DESTDIR/usr" ]; then cp -a "$DESTDIR/usr/." "$DESTDIR/" && rm -rf "$DESTDIR/usr"; fi
if [ -d "$DESTDIR/lib64" ]; then cp -a "$DESTDIR/lib64/." "$DESTDIR/lib/" && rm -rf "$DESTDIR/lib64"; fi
find $DESTDIR/bin -type f -exec llvm-strip --strip-all {} \; 2>/dev/null || true"""

[depends]
runtime = []
build = ["go"]
