[package]
name = "cni-plugins"
version = "1.9.1"
license = "Apache-2.0"
pre_bootstrap = false
description = "CNI network plugins for container networking"

[build]
system = "custom"
build = ""
install = ""

[depends]
runtime = ["musl"]
build = []
