[package]
name = "jq"
version = "1.8.1"
license = "MIT"
description = "Lightweight and flexible command-line JSON processor"

[source]
url = "https://github.com/jqlang/jq/releases/download/jq-1.8.1/jq-1.8.1.tar.gz"
sha256 = "2be64e7129cecb11d5906290eba10af694fb9e3e7f9fc208a311dc33ca837eb0"

[build]
system = "custom"
build = """set -e
GREP=/bin/grep EGREP="/bin/grep -E" FGREP="/bin/grep -F" \
  CC=clang \
  CFLAGS="-O2 -fomit-frame-pointer --rtlib=compiler-rt --unwindlib=libunwind" \
  LDFLAGS="-fuse-ld=lld --rtlib=compiler-rt --unwindlib=libunwind -Wl,--disable-new-dtags" \
  ./configure \
    --prefix=/ \
    --bindir=/bin \
    --disable-shared \
    --enable-static \
    --with-oniguruma=builtin \
    --disable-rpath \
    --disable-docs
make -j$(nproc)
"""
install = """set -e
make DESTDIR=$DESTDIR install
if [ -d "$DESTDIR/usr" ]; then cp -a "$DESTDIR/usr/." "$DESTDIR/" && rm -rf "$DESTDIR/usr"; fi
if [ -d "$DESTDIR/lib64" ]; then cp -a "$DESTDIR/lib64/." "$DESTDIR/lib/" && rm -rf "$DESTDIR/lib64"; fi
rm -rf "$DESTDIR/share/doc" "$DESTDIR/share/man" "$DESTDIR/include"
find "$DESTDIR/lib" -name "*.la" -delete 2>/dev/null || true
find "$DESTDIR/bin" -type f -exec llvm-strip --strip-all {} \; 2>/dev/null || true
find "$DESTDIR/lib" -name "*.so*" -type f -exec llvm-strip --strip-unneeded {} \; 2>/dev/null || true"""

[depends]
runtime = ["musl"]
build = ["clang", "make", "exproxide", "jonerix-headers"]
