[package]
name = "openssl"
version = "3.4.1"
license = "Apache-2.0"
pre_bootstrap = false
description = "TLS/SSL and cryptography library"

[build]
system = "custom"
build = ""
install = ""

[depends]
runtime = ["musl"]
build = []
