[package]
name = "mksh"
version = "R59c"
license = "MirOS"
pre_bootstrap = false
description = "MirBSD Korn Shell"

[build]
system = "custom"
build = ""
install = ""

[depends]
runtime = ["musl"]
build = []
