#!/usr/bin/env bash
# Worktree boot script
# Generated by: cas init
#
# Usage: ./scripts/worktree-boot.sh [slot]
#
# This script:
# 1. Generates .env.worktree with assigned SLOT
# 2. Exports the variables for subsequent commands in this shell

set -euo pipefail

SLOT="${1:-1}"
OUTPUT=".env.worktree"

# Generate .env.worktree directly
cat > "$OUTPUT" <<EOF
# Worktree environment
# Generated by: scripts/worktree-boot.sh
#
# SLOT is assigned automatically. Use it to derive unique ports or names.

SLOT=$SLOT

# Example port offsets (SLOT * 10):
# WEB_PORT=\$((3000 + (SLOT * 10)))
# API_PORT=\$((8080 + (SLOT * 10)))
# DB_PORT=\$((5432 + (SLOT * 10)))
#
# Example shared-database isolation:
# DATABASE_NAME=myapp_slot\${SLOT}
#
# iOS Simulator UDID:
# SIM_UDID=
EOF
echo "Generated $OUTPUT with SLOT=$SLOT"

# Source the generated env
if [[ -f "$OUTPUT" ]]; then
    set -a
    source "$OUTPUT"
    set +a
fi

echo "Environment prepared from $OUTPUT"
echo "Run your project-specific dev command next."
