[package]
name = "zstd"
version = "1.5.6"
license = "BSD-3-Clause"
pre_bootstrap = false
description = "Zstandard compression library and tool"

[build]
system = "custom"
build = ""
install = ""

[depends]
runtime = ["musl"]
build = []
