[package]
name = "flex"
version = "2.6.4"
license = "BSD-2-Clause"
pre_bootstrap = false
description = "Fast lexical analyzer generator"

[build]
system = "custom"
build = ""
install = ""

[depends]
runtime = ["musl"]
build = []
