[package]
name = "ripgrep"
version = "15.1.0"
license = "MIT"
pre_bootstrap = false
description = "Fast line-oriented search tool (grep replacement)"

[build]
system = "custom"
build = ""
install = ""

[depends]
runtime = ["musl"]
build = []
