[package]
name = "pip"
version = "25.1.1"
license = "MIT"
pre_bootstrap = false
description = "Python package installer"

[build]
system = "custom"
build = ""
install = ""

[depends]
runtime = ["python3"]
build = []
