[package]
name = "samurai"
version = "1.2"
license = "Apache-2.0"
pre_bootstrap = false
description = "ninja-compatible build tool written in C"

[build]
system = "custom"
build = ""
install = ""

[depends]
runtime = ["musl"]
build = []
