[package]
name = "samurai"
version = "1.2"
license = "Apache-2.0"
pre_bootstrap = false
description = "ninja-compatible build tool written in C"

[source]
url = "sources/samurai-1.2.tar.gz"  # vendored in sources/
sha256 = "37a2d9f35f338c53387eba210bab7e5d8abe033492664984704ad84f91b71bac"

[build]
system = "custom"
build = "make CC=clang CFLAGS=\"-O2 -fomit-frame-pointer\" PREFIX=/"
install = """make PREFIX=/ DESTDIR=$DESTDIR install
if [ -d "$DESTDIR/usr" ]; then cp -a "$DESTDIR/usr/." "$DESTDIR/" && rm -rf "$DESTDIR/usr"; fi
if [ -d "$DESTDIR/lib64" ]; then cp -a "$DESTDIR/lib64/." "$DESTDIR/lib/" && rm -rf "$DESTDIR/lib64"; fi
find $DESTDIR/bin -type f -exec llvm-strip --strip-all {} \; 2>/dev/null || true
find $DESTDIR/lib -name "*.so*" -type f -exec llvm-strip --strip-unneeded {} \; 2>/dev/null || true"""

[depends]
runtime = ["musl"]
build = ["clang", "make"]
